### ISSUE TITLE
The documentation search seems to be indexing the sidebar, not just the main content

### ISSUE THREAD

**Issue by macbookandrew** [rappasoft/laravel-livewire-tables#1097]
The [documentation](https://rappasoft.com/docs/laravel-livewire-tables/v2/) search seems to be indexing the contents of the sidebar, not just the main content.

Searching for any term that’s visible in the sidebar brings up huge list of mostly-irrelevant results:

![Screenshot 2023-03-10 at 16 45 17](https://user-images.githubusercontent.com/784333/224442418-df959ad7-73f3-4694-b76f-53b94da6ab6a.png)

Is it possible to update the index to include only the content?

**Comment by lrljoe** [comment]
I believe this is using Algolia so should be fixable, but is something that only @rappasoft can sort as the config for this isn't in the docs section of the package.

**Comment by lrljoe** [comment]
Did you have an outstanding question by the way?  If so let me know and I'll see if I can help

**Comment by macbookandrew** [comment]
Indexing the titles makes total sense. The issue is that the contents of the sidebar appear to be included for **every** document instead of just the relevant documents,, rendering search almost useless IMHO 🤷🏻‍♂️

**Comment by lrljoe** [comment]
Oh jeez, I've just tried searching for "sort" and I completely see what you mean... 

Hopefully Anthony won't mind me assigning this one to him as I'm powerless to help in this case sadly!

I know he's pretty busy at the moment, but do expect this to be fixed!  If there's anything I can help with in the meantime, just raise an issue and I'm usually pretty responsive.

**Comment by macbookandrew** [comment]
@rappasoft bump to keep this open 🙂

**Comment by lrljoe** [comment]
I've given him a nudge on this too.

**Comment by rappasoft** [comment]
Hey all. I actually use the same code that Spatie used on their docs site. I'm assuming I'm using the wrong headers for sections or something that Algolia is looking for to index the different areas. I'll take a look at Spatie and see where I'm differing and try to fix it.

Thanks.

**Comment by lrljoe** [comment]
May be as simple as wrapping the titles/headers with

```
<div data-no-index>
           Header goes here 
</div>
```

**Comment by rappasoft** [comment]
Ok I made some changes both to the docs site and to Algolia, if I did it right it should reindex 9am EST tomorrow morning and we can see if its any better. I honestly never used the search because I know where everything is so I didn't know it was broken. Thanks for bringing it to my attention.

**Comment by rappasoft** [comment]
Try the doc search again, It should be working better.

**Comment by macbookandrew** [comment]
@rappasoft thanks, but I’m still seeing the same behavior 🤷🏻‍♂️

**Comment by macbookandrew** [comment]
Thanks!!
