### ISSUE TITLE
[Bug]: Missing table header class

### ISSUE THREAD

**Issue by danie-ramdhani** [rappasoft/laravel-livewire-tables#1981]
### What happened?

The table header when the column is not sortable, the class is not applied to the label correctly:

![Screenshot 2024-09-30 015253](https://github.com/user-attachments/assets/3b2ee7db-0791-439b-b0e1-fcbeb7f9ba69)

### Package Version

3.4.21

### PHP Version

None

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
This should be fixed in 3.5.0, please let me know if not the case!

**Comment by danie-ramdhani** [comment]
i've upgrade to latest version (3.5.0) and it still missing. and its not the table header class, but the element inside it 😅.

<img width="769" alt="image" src="https://github.com/user-attachments/assets/4be030e9-396a-4aaa-8ff7-4347c71b5736">

**Comment by lrljoe** [comment]
Can you share what you're doing to create that Column please?

Do you have any custom setThAttributes/setTdAttributes/setTrAttributes in your configure?

**Comment by danie-ramdhani** [comment]
i just have regular custom class.

<img width="431" alt="image" src="https://github.com/user-attachments/assets/583ac1d6-d886-4514-b5c7-f72a1fb17779">

to reproduce it is simple. create column that use `sortable()` and another column is not using it.

<img width="574" alt="image" src="https://github.com/user-attachments/assets/783538eb-ed5f-4e32-ab61-dd98d9c411a3">

**Comment by lrljoe** [comment]
> i just have regular custom class.

Just to validate - have you previously published the views?

Will try to replicate what you've got, to see if I can reproduce.

**Comment by danie-ramdhani** [comment]
No i don't.

**Comment by lrljoe** [comment]
> No i don't.

Just so I can narrow it down a bit

```
  $this->setThSortButtonAttributes(function(Column $column) {
    if ($column->isField('deleted_at')) {
      return [
        'class' => 'bg-green-500',
      ];
    }
 
    return [];
  });
```

I do need to get it all back in alignment, but this should help me focus where the issue is:

**Comment by danie-ramdhani** [comment]
ok, so tried it. and when the column is not sortable, it doens't apply the styles:

```php
$this->setThSortButtonAttributes(function (Column $column) {
    if ($column->isField('avatar')) {
        return [
            'class' => 'bg-green-500',
        ];
    }

    if ($column->isField('role')) {
        return [
            'class' => 'bg-green-500',
        ];
    }

    return [];
});
```

result:

<img width="155" alt="image" src="https://github.com/user-attachments/assets/fb8bcf34-ac51-45e2-9606-98fb39c21c16">


like i said before the `sortable` column is wrapped inside the button (and all the styles is only on the button, not span element)

<img width="446" alt="image" src="https://github.com/user-attachments/assets/7083bb58-24b6-4647-91f0-35cea4216766">

**Comment by lrljoe** [comment]
Thanks for the detail, I'll try to get a fix out this weekend.

**Comment by lrljoe** [comment]
Hmmm

```
$this->setThSortButtonAttributes(function (Column $column) {
    if ($column->isField('avatar')) {
        return [
            'class' => 'bg-green-500',
        ];
    }

    if ($column->isField('role')) {
        return [
            'class' => 'bg-green-500',
        ];
    }

    return [];
});

```
IS working as expected.

It's applying the "class" attribute you selected (bg-green-500) to the button element for "role".    
The Column "avatar" isn't a sortable Column.

![image](https://github.com/user-attachments/assets/d9740bc0-ab21-424c-b665-8efa353ecb45)

**Comment by lrljoe** [comment]
You'd want the "setLabelAttributes" for a Column to set the attributes for the "span", from what I recall.
